# Generated by Django 4.2.1 on 2023-05-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_created_at_job_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
